### ISSUE TITLE
Why it cannot be ran

### ISSUE THREAD

**Issue by Mooos-MoSheng** [twt-tec/Silent-Writing-Master#3]
I‘m using Linux(Ubuntu x64),and cannot run this code.

**Comment by Mooos-MoSheng** [comment]
I‘m using Linux(Ubuntu x64),and cannot run this code

**Comment by edge-bird** [comment]
Maybe they use Windows enviroment

**Comment by coldiceh** [comment]
#include <windows.h> /se

**Comment by Mooos-MoSheng** [comment]
What about the Linux Users

**Comment by Acfboy** [comment]
@Mooos-MoSheng 

> What about the Linux Users

~~负责任地告诉你，Linux 用户不需要这玩意儿~~

`system` 在 `Linux` 下照样可用，把 `windows.h` 去掉，用 `cstdlib` 再写个 `ifdef` 就可以了啊。

**Comment by Acfboy** [comment]
在 `Ubuntu` 上显示颜色可以参照[这里](https://acfboy.pw/post/wo-shi-yong-ubuntu-linux-yi-zhou-nian-la/)

**Comment by Mooos-MoSheng** [comment]
> @Mooos-MoSheng
> 
> > What about the Linux Users
> 
> ~负责任地告诉你，Linux 用户不需要这玩意儿~
> 
> `system` 在 `Linux` 下照样可用，把 `windows.h` 去掉，用 `cstdlib` 再写个 `ifdef` 就可以了啊。

~~负责任地告诉你，我就是Linux用户~~

问题是体验会变得更差，能否做到Linux和Windows下相同体验()
